### ISSUE TITLE
500 服务器内部出现错误，请查看日志

### ISSUE THREAD

**Issue by ShimmerLS** [chengzhongxue/plugin-douban#1]
halo版本：1.12.4
主题：[halo-theme-hao](https://githubfast.com/liuzhihang/halo-theme-hao)：1.4.8
插件版本：1.1.0
现像：插件清空了数据之后能正常进入``/douban`` 页面。插件同步数据了之后就报500 的错误

[halo.log](https://github.com/chengzhongxue/plugin-douban/files/14417466/halo.log)

**Comment by AAAAAAlon** [comment]
我也是进入/douban页面会500， 看日志貌似是有个报错`class path resource [templates/douban.html] cannot be opened because it does not exist` ,是只有特定的主题才能用这个插件吗？

**Comment by chengzhongxue** [comment]
hao主题适配问题
