### ISSUE TITLE
在文章里添加豆瓣链接，图片显示异常以及黑暗主题下效果不佳

### ISSUE THREAD

**Issue by isqilinlin** [chengzhongxue/plugin-douban#2]
编辑器没有问题：
![image](https://github.com/chengzhongxue/plugin-douban/assets/107522343/7ac18b76-5906-4ae5-b0a9-e986ca16a81a)

效果是这样的：
![image](https://github.com/chengzhongxue/plugin-douban/assets/107522343/dd4296f3-7538-4c44-b531-7c1d2ac3325d)

Halo：
2.13.1

豆瓣插件：
1.1.4

服务器是东京的，是否有这个因素干扰未知。

**Comment by chengzhongxue** [comment]
暗色这个得主题自己适配
图片目前有点问题在修复

**Comment by chengzhongxue** [comment]
下个版本解决这个问题吧
