### ISSUE TITLE
同步数据时，后台报错 400，无法同步

### ISSUE THREAD

**Issue by tyronczt** [chengzhongxue/plugin-douban#4]
halo版本：2.15.2
主题：[theme-iemo](https://github.com/chengzhongxue/halo-theme-iemo)：1.0.1
插件版本：1.1.7
现象：首次安装halo，并安装豆瓣插件，配置个人信息
![Snipaste_2024-06-07_11-38-41](https://github.com/chengzhongxue/plugin-douban/assets/16408276/a000ff99-57bb-46c6-9217-c87b8f3bd5fb)
一直同步不了，查看报错日志：
java.io.IOException: Server returned HTTP response code: 400 for URL: https://fatesinger.com/dbapi/user/tyronchen?_dtcc=1&_i=7729893hrPpt4x/interests?count=49&start=0&type=drama&status=mark
![报错日志](https://github.com/chengzhongxue/plugin-douban/assets/16408276/2380a68e-0f1a-43d5-a72f-5ad370716b75)

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/plugin-douban/assets/89380218/c8a588f0-0f81-4fa6-b779-8801c5571e8f)

**Comment by chengzhongxue** [comment]
id就好了，你搞个这个是什么鬼东西

**Comment by tyronczt** [comment]
好吧，是我的问题，调整后已经同步出来了

**Comment by chengzhongxue** [comment]
> 好吧，是我的问题，调整后已经同步出来了

没问题就好
