### ISSUE TITLE
前端应该按观看时间排序比较合理

### ISSUE THREAD

**Issue by uubbbb** [chengzhongxue/plugin-douban#5]
目前我看前端条目应该是按照creationTimestamp排序的，第一次同步数据的时候，越早标记的条目入库的时间越晚，在前端的排序就越在前面，比如我现在打开网站豆瓣页面，都是好几年前我最开始标记的条目。应该改成按观看时间排序，我最近看的电影排在最前面。

**Comment by chengzhongxue** [comment]
给个你地址我看看

**Comment by uubbbb** [comment]
http://149.28.15.122:8090/douban   
比如这个地址，现在排在最前面的是我最早添加的，2022年12月，然后是2023年1月，2023年2月，一直到现在。第一次同步的时候就是这样，越早标记的越晚入库。后面我新添加的条目，因为入库的晚，所以会排在最前面，排序就正常了。
而且按标记时间排序也方便我在后台修改，我可能不会第一时间在豆瓣标记，后面再补标的。

**Comment by chengzhongxue** [comment]
https://demo.kunkunyu.com/upload/plugin-douban-1.1.9-1.jar
试试这个包

**Comment by uubbbb** [comment]
现在可以按观看时间排序了，感谢🙏
